In [1]:
import numpy as np

demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[:, (1,2)]

C:\Users\164118\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")


array([[35, 74],
       [37, 37],
       [39, 93]])

In [2]:
demo_array=np.arange(0,10)


In [3]:
demo_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
demo_array <3


array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [5]:
demo_array[demo_array <6]


array([0, 1, 2, 3, 4, 5])

In [6]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [7]:
demo_matrix[2,3]


39

In [8]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [9]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [10]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [11]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [13]:
from collections import defaultdict
s = [('yellow', 1), ('blue', 2), ('yellow', 3), ('blue', 4), ('red', 1)]
dict = defaultdict(list)
for i, j in s :
    print(i, j)
    dict[i].append(j)
    print (dict.items())

#print(dict.get())

yellow 1
dict_items([('yellow', [1])])
blue 2
dict_items([('yellow', [1]), ('blue', [2])])
yellow 3
dict_items([('yellow', [1, 3]), ('blue', [2])])
blue 4
dict_items([('yellow', [1, 3]), ('blue', [2, 4])])
red 1
dict_items([('yellow', [1, 3]), ('blue', [2, 4]), ('red', [1])])


In [14]:
def listavg(list_of_nums):
    for num in list_of_nums:
        num += num
    return (num/len(list_of_nums))
    

a = [7, 8, 4, 6]
print(listavg(a))

3.0


In [15]:
string = "seller_id, product_id, price, customer_id, review_id"
string.split()

['seller_id,', 'product_id,', 'price,', 'customer_id,', 'review_id']

In [16]:
import numpy as np
dataset = [
    {'customer_id':1, 'review_date' : '2016-01-05', 'last_updated': '2017-01-06', 'review': 'very good place' },
    {'customer_id':2, 'review_date' : '2018-01-06', 'last_updated': '2018-01-05', 'review': 'very good place'},
    {'customer_id':3, 'review_date' : '' , 'last_updated': '2018-01-05', 'review': 'very good place'},
    {'customer_id':4, 'review_date' : '2017-01-08', 'last_updated': '2018-01-05', 'review': 'very good place'},
    {'customer_id':4, 'review_date' : '2016-01-01', 'last_updated': '2018-01-05', 'review': 'very horrible place'},
    {'customer_id':4, 'review_date' : '2018-01-02', 'last_updated': '2018-01-05', 'review': 'very bad place'},
    {'customer_id':2, 'review_date' : '2019-01-03', 'last_updated': '2018-01-05', 'review': ''},
    {'customer_id':3, 'review_date' : '2019-01-05', 'last_updated': '2018-01-05', 'review': ''},
    {'customer_id':1, 'review_date' : '2017-01-06', 'last_updated': '2017-02-05', 'review': ''},
    {'customer_id':1, 'review_date' : '2017-01-08', 'last_updated': '2017-02-05', 'review': 'very good place'},
    {'customer_id':5, 'review_date' : '2019-01-08', 'last_updated': '2019-02-05', 'review': 'very good place'}
]
print(dataset[0])
print(len(dataset))
print(dataset[0]['review_date'][:4])
#dataset = [d for d in s if ]

{'customer_id': 1, 'review_date': '2016-01-05', 'last_updated': '2017-01-06', 'review': 'very good place'}
11
2016


In [17]:
dataset = [d for d in dataset if (d['review_date'][:4] != "") and int(d['review_date'][:4]) <= 2018 ]
print(len(dataset))
print (dataset)

7
[{'customer_id': 1, 'review_date': '2016-01-05', 'last_updated': '2017-01-06', 'review': 'very good place'}, {'customer_id': 2, 'review_date': '2018-01-06', 'last_updated': '2018-01-05', 'review': 'very good place'}, {'customer_id': 4, 'review_date': '2017-01-08', 'last_updated': '2018-01-05', 'review': 'very good place'}, {'customer_id': 4, 'review_date': '2016-01-01', 'last_updated': '2018-01-05', 'review': 'very horrible place'}, {'customer_id': 4, 'review_date': '2018-01-02', 'last_updated': '2018-01-05', 'review': 'very bad place'}, {'customer_id': 1, 'review_date': '2017-01-06', 'last_updated': '2017-02-05', 'review': ''}, {'customer_id': 1, 'review_date': '2017-01-08', 'last_updated': '2017-02-05', 'review': 'very good place'}]


In [18]:
from collections import defaultdict
test = defaultdict(int)

for d in dataset:    
    test[d['customer_id']] += 1
    
print(test)
print("\n")
print("count of items for customer_id 2 is: ", test[d['customer_id']]>1)

defaultdict(<class 'int'>, {1: 3, 2: 1, 4: 3})


count of items for customer_id 2 is:  True


In [19]:
sampleSet = set()
a = 1

filtereddata=[sampleSet.update(d['review'].split()) for d in dataset if test[d['customer_id']]>2 
              and int(d['last_updated'][:4]) >= 2018 and d['review_date'] != '' and len(d['review'].split()) > 1]

print("Filtered records <%s> "%(len(filtereddata)))
print("filtered words to look for context :- ", sampleSet)

Filtered records <3> 
filtered words to look for context :-  {'place', 'bad', 'good', 'horrible', 'very'}


In [20]:
import time
timestr = "2018-07-26 01:36:02"
timeobj = time.strptime(timestr, "%Y-%m-%d %H:%M:%S")

In [21]:
timeobj

time.struct_time(tm_year=2018, tm_mon=7, tm_mday=26, tm_hour=1, tm_min=36, tm_sec=2, tm_wday=3, tm_yday=207, tm_isdst=-1)

In [31]:
import calendar
t1 = calendar.timegm(timeobj)
t2 = time.mktime(timeobj) #unix time number

In [26]:
t1, t2 #to convert as number for faster arithmatic operations

(1532568962, 1532586962.0)

In [25]:
t1 + 60*60*24*5 #for getting value of 5 days later

1533000962

In [29]:
#to get back in readable format
time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(t1))

'2018-07-26 01:36:02'

In [32]:
time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(t1 + 60*60*24*5))

'2018-07-31 01:36:02'

In [30]:
help(time.strptime)

Help on built-in function strptime in module time:

strptime(...)
    strptime(string, format) -> struct_time
    
    Parse a string to a time tuple according to a format specification.
    See the library reference manual for formatting codes (same as
    strftime()).
    
    Commonly used format codes:
    
    %Y  Year with century as a decimal number.
    %m  Month as a decimal number [01,12].
    %d  Day of the month as a decimal number [01,31].
    %H  Hour (24-hour clock) as a decimal number [00,23].
    %M  Minute as a decimal number [00,59].
    %S  Second as a decimal number [00,61].
    %z  Time zone offset from UTC.
    %a  Locale's abbreviated weekday name.
    %A  Locale's full weekday name.
    %b  Locale's abbreviated month name.
    %B  Locale's full month name.
    %c  Locale's appropriate date and time representation.
    %I  Hour (12-hour clock) as a decimal number [01,12].
    %p  Locale's equivalent of either AM or PM.
    
    Other codes may be available on yo